const productsData = [
  {
    "id": 1,
    "title": "Bacon and Caramelized Onions Pinsa",
    "title_fr": "Pinsa au Bacon et Oignons Caramélisés",
    "title_es": "Pinsa de Tocino y Cebollas Caramelizadas",
    "category": "Frozen Pinsa",
    "category_fr": "Pinsa surgelée",
    "category_es": "Pinsa congelada",
    "image": "bacon-and-caramelized-onions-pinsa.webp",
    "description": "Martha Stewart Bacon and Caramelized Onions Pinsa pairs savory bacon and sweet caramelized onions with creamy Alfredo sauce, mozzarella and Parmesan on a hand-stretched, authentic Roman-style crust. Light and airy with a crisp exterior, the pinsa crust creates the perfect base for this rich, savory and slightly sweet combination. Ready in minutes, it's an effortless way to enjoy a distinctive Roman-inspired meal at home.",
    "description_fr": "La pinsa au bacon et oignons caramélisés Martha Stewart marie du bacon savoureux et de doux oignons caramélisés avec une sauce Alfredo crémeuse, de la mozzarella et du parmesan sur une croûte romaine artisanale étirée à la main. Légère, aérée et croustillante à l'extérieur, elle offre un équilibre gourmand entre saveurs salées et notes douces. Prête en quelques minutes pour un repas d'inspiration romaine chez soi.",
    "description_es": "La pinsa de tocino y cebollas caramelizadas Martha Stewart combina sabroso tocino y dulces cebollas caramelizadas con cremosa salsa Alfredo, mozzarella y parmesano sobre una masa artesanal de estilo romano estirada a mano. Ligera y crujiente por fuera, crea la base perfecta para esta combinación rica, salada y sutilmente dulce. Lista en minutos para disfrutar en casa.",
    "features": "Featuring: Alfredo sauce, mozzarella, Parmesan, caramelized onions and bacon",
    "features_fr": "Caractéristiques : Sauce Alfredo, mozzarella, parmesan, oignons caramélisés et bacon",
    "features_es": "Características: Salsa Alfredo, mozzarella, parmesano, cebollas caramelizadas y tocino",
    "gallery": [
      "bacon-and-caramelized-onions-pinsa-gallery-1.webp",
      "bacon-and-caramelized-onions-pinsa-gallery-2.webp",
      "bacon-and-caramelized-onions-pinsa-gallery-3.webp",
      "bacon-and-caramelized-onions-pinsa-gallery-4.webp",
      "bacon-and-caramelized-onions-pinsa-gallery-5.webp"
    ],
    "ingredients": "Ingredients: Pinsa (wheat flour, organic rice flour, organic fava flour, sourdough yeast, water, olive oil, salt, yeast [yeast, sorbitan monostearate, ascorbic acid]). Toppings: Mozzarella cheese (milk, modified milk ingredients, cream, salt, calcium chloride, bacterial culture, microbial enzyme), Caramelized ONIONSs (ONIONSs, natural flavour), Bacon (pork, water, salt, brown sugar, smoked sugar, sodium phosphate, sodium erythorbate, sodium nitrite, spices), Parmesan cheese (milk, salt, lipase, microbial enzyme, bacterial culture, calcium chloride, cellulose). Alfredo sauce: Cream (cream, milk, carrageenan, cellulose gum, mono and diglycerides, polysorbate 80), Minced garlic, Parmesan cheese (milk, salt, lipase, microbial enzyme, bacterial culture, calcium chloride, cellulose), Modified corn starch, Salt, Black pepper.\nContains: Wheat, Milk.\nMay contain: Eggs, Soy, Mustard.",
    "ingredients_fr": "Ingrédients : Pinsa (farine de blé, farine de riz biologique, farine de fève biologique, levain naturel, eau, huile d'olive, sel, levure). Garnitures : Fromage mozzarella, oignons caramélisés, bacon (porc, eau, sel, sucre brun, épices), fromage parmesan. Sauce Alfredo : Crème, ail émincé, fromage parmesan, amidon de maïs modifié, sel, poivre noir.\nContient : Blé, Lait.\nPeut contenir : Œufs, Soja, Moutarde.",
    "ingredients_es": "Ingredientes: Masa de pinsa (harina de trigo, harina de arroz orgánica, harina de haba orgánica, masa madre, agua, aceite de oliva, sal, levadura). Coberturas: Queso mozzarella, cebollas caramelizadas, tocino (cerdo, agua, sal, azúcar moreno, especias), queso parmesano. Salsa Alfredo: Crema, ajo picado, queso parmesano, almidón de maíz modificado, sal, pimienta negra.\nContiene: Trigo, Leche.\nPuede contener: Huevos, Soya, Mostaza.",
    "slug": "bacon-and-caramelized-onions-pinsa",
    "image_ca": "",
    "image_us": "bacon-and-caramelized-onions-pinsa-us.webp",
    "gallery_ca": [],
    "gallery_us": [
      "bacon-and-caramelized-onions-pinsa-us-gallery-1.webp",
      "bacon-and-caramelized-onions-pinsa-us-gallery-2.webp",
      "bacon-and-caramelized-onions-pinsa-us-gallery-3.webp",
      "bacon-and-caramelized-onions-pinsa-us-gallery-4.webp",
      "bacon-and-caramelized-onions-pinsa-us-gallery-5.webp"
    ]
  },
  {
    "id": 2,
    "title": "Bacon and Caramelized Onions Pizza",
    "title_fr": "Pizza au Bacon et Oignons Caramélisés",
    "title_es": "Pizza de Tocino y Cebollas Caramelizadas",
    "category": "Frozen Pizza",
    "category_fr": "Pizza surgelée",
    "category_es": "Pizza congelada",
    "image": "Bacon-and-Caramelized-Onions-Frozen-Pizza.webp",
    "description": "Martha Stewart Bacon and Caramelized Onions Pizza pairs savory bacon and sweet caramelized onions with creamy Alfredo sauce, mozzarella and Parmesan on a hand-stretched, stone-baked crust. Rich, savory and slightly sweet, this indulgent combination delivers layers of flavor in every bite. Simply bake until golden for a pizzeria-inspired pizza that's ready to enjoy at home in minutes.",
    "description_fr": "La pizza au bacon et oignons caramélisés Martha Stewart associe du bacon fumé savoureux et des oignons caramélisés fondants à une sauce Alfredo onctueuse, de la mozzarella et du parmesan sur une pâte cuite sur pierre étirée à la main. Riche et généreuse, elle offre un festival de saveurs à chaque bouchée. À cuire au four jusqu'à ce qu'elle soit bien dorée.",
    "description_es": "La pizza de tocino y cebollas caramelizadas Martha Stewart combina sabroso tocino y cebollas caramelizadas con salsa Alfredo cremosa, mozzarella y parmesano sobre una base horneada a la piedra estirada a mano. Rica, indulgente y perfectamente equilibrada, lista en minutos.",
    "features": "Featuring: Alfredo sauce, mozzarella, Parmesan, caramelized onions and bacon",
    "features_fr": "Caractéristiques : Sauce Alfredo, mozzarella, parmesan, oignons caramélisés et bacon",
    "features_es": "Características: Salsa Alfredo, mozzarella, parmesano, cebollas caramelizadas y tocino",
    "gallery": [],
    "ingredients": "Ingredients: Wheat flour, water, mozzarella cheese, caramelized onions, bacon, alfredo sauce, parmesan, olive oil, salt, yeast.\nContains: Wheat, Milk.",
    "ingredients_fr": "Ingrédients : Farine de blé, eau, fromage mozzarella, oignons caramélisés, bacon, sauce alfredo, parmesan, huile d'olive, sel, levure.\nContient : Blé, Lait.",
    "ingredients_es": "Ingredientes: Harina de trigo, agua, queso mozzarella, cebollas caramelizadas, tocino, salsa alfredo, queso parmesano, aceite de oliva, sal, levadura.\nContiene: Trigo, Leche."
  },
  {
    "id": 3,
    "title": "Balsamic Garlic & Herb Infused Extra Virgin Olive Oil",
    "title_fr": "Huile d'Olive Extra Vierge Infusée au Balsamique, Ail et Herbes",
    "title_es": "Aceite de Oliva Virgen Extra Infusionado con Balsámico, Ajo y Hierbas",
    "category": "Infused Oils",
    "category_fr": "Huiles infusées",
    "category_es": "Aceites infusionados",
    "image": "Balsamic-Garlic-and-Herb-Infused-Extra-Virgin-Olive-Oil.webp",
    "description": "Martha Stewart Balsamic Garlic & Herb Infused Extra Virgin Olive Oil combines extra virgin olive oil with balsamic vinegar, basil, garlic, oregano, thyme and a touch of crushed red pepper. Rich, aromatic and wonderfully versatile, it brings an extra layer of flavor to oven-baked pizzas and makes an effortless base for salad dressings and vinaigrettes. Drizzle it over fresh bread, roasted vegetables or your favorite dishes for an easy finishing touch.",
    "description_fr": "L'huile d'olive extra vierge infusée au vinaigre balsamique, ail et fines herbes Martha Stewart allie une huile d'olive de première pression à du vinaigre balsamique, basilic, ail, origan, thym et piment broyé. Aromatique et polyvalente, elle rehausse les pizzas, vinaigrettes et légumes rôtis.",
    "description_es": "El aceite de oliva virgen extra infusionado con balsámico, ajo y hierbas Martha Stewart combina aceite virgen extra con vinagre balsámico, albahaca, ajo, orégano, tomillo y pimiento rojo triturado. Aromático y versátil, ideal para pizzas, panes y aderezos.",
    "features": "Featuring: Extra-virgin olive oil, balsamic vinegar, garlic, basil, oregano and thyme",
    "features_fr": "Caractéristiques : Huile d'olive extra vierge, vinaigre balsamique, ail, basilic, origan et thym",
    "features_es": "Características: Aceite de oliva virgen extra, vinagre balsámico, ajo, albahaca, orégano y tomillo",
    "gallery": [],
    "ingredients": "Ingredients: Extra-virgin olive oil, balsamic vinegar, basil, crushed red pepper, garlic, oregano, thyme, natural flavorings (liquid garlic flavor).",
    "ingredients_fr": "Ingrédients : Huile d'olive extra vierge, vinaigre balsamique, basilic, piment rouge broyé, ail, origan, thym, arômes naturels d'ail.",
    "ingredients_es": "Ingredientes: Aceite de oliva virgen extra, vinagre balsámico, albahaca, pimiento rojo triturado, ajo, orégano, tomillo, aromas naturales de ajo."
  },
  {
    "id": 4,
    "title": "Cacio e Pepe with Alfredo Sauce Pizza",
    "title_fr": "Pizza Cacio e Pepe à la Sauce Alfredo",
    "title_es": "Pizza Cacio e Pepe con Salsa Alfredo",
    "category": "Frozen Pizza",
    "category_fr": "Pizza surgelée",
    "category_es": "Pizza congelada",
    "image": "Cacio-e-Pepe-with-Alfredo-Sauce-Frozen-Pizza.webp",
    "description": "Martha Stewart Cacio e Pepe with Alfredo Sauce Pizza takes inspiration from the classic Italian pasta dish, pairing creamy Alfredo sauce with Parmesan, Romano cheese, minced garlic and black pepper on a hand-stretched, stone-baked crust. Rich and cheesy with a distinctive peppery finish, this white pizza offers an elevated alternative to traditional tomato-based varieties. Bake until golden for an easy, pizzeria-inspired meal at home.",
    "description_fr": "Inspirée du grand classique romain, la pizza Cacio e Pepe Martha Stewart allie une sauce Alfredo onctueuse, du parmesan, du pecorino romano, de l'ail émincé et du poivre noir moulu sur une pâte artisanale cuite sur pierre. Une alternative blanche raffinée et gourmande.",
    "description_es": "Inspirada en el clásico romano, la pizza Cacio e Pepe con salsa Alfredo Martha Stewart combina salsa cremosa con parmesano, queso romano, ajo picado y pimienta negra sobre una masa horneada a la piedra. Una opción blanca gourmet para saborear en casa.",
    "features": "Featuring: Alfredo sauce, minced garlic, Parmesan, Romano cheese and black pepper",
    "features_fr": "Caractéristiques : Sauce Alfredo, ail émincé, parmesan, fromage romano et poivre noir",
    "features_es": "Características: Salsa Alfredo, ajo picado, parmesano, queso romano y pimienta negra",
    "gallery": [],
    "ingredients": "Ingredients: Wheat flour, water, alfredo sauce, parmesan cheese, romano cheese, minced garlic, black pepper, olive oil, salt, yeast.\nContains: Wheat, Milk.",
    "ingredients_fr": "Ingrédients : Farine de blé, eau, sauce alfredo, fromage parmesan, fromage romano, ail haché, poivre noir, huile d'olive, sel, levure.\nContient : Blé, Lait.",
    "ingredients_es": "Ingredientes: Harina de trigo, agua, salsa alfredo, queso parmesano, queso romano, ajo picado, pimienta negra, aceite de oliva, sal, levadura.\nContiene: Trigo, Leche."
  },
  {
    "id": 5,
    "title": "Lemon Pepper Infused Extra Virgin Olive Oil",
    "title_fr": "Huile d'Olive Extra Vierge Infusée au Citron et Poivre Noir",
    "title_es": "Aceite de Oliva Virgen Extra Infusionado con Limón y Pimienta",
    "category": "Infused Oils",
    "category_fr": "Huiles infusées",
    "category_es": "Aceites infusionados",
    "image": "Lemon-Pepper-Infused-Extra-Virgin-Olive-Oil.webp",
    "description": "Martha Stewart Lemon Pepper Infused Extra Virgin Olive Oil combines extra virgin olive oil with black peppercorns and dried lemon peel for a bright, zesty flavor with a peppery finish. Fresh and versatile, it adds a burst of flavor to oven-baked pizzas and pairs beautifully with grilled fish, roasted chicken and vegetables. Mix it with fresh herbs and lemon juice for a simple, flavorful dressing or marinade.",
    "description_fr": "L'huile d'olive extra vierge infusée au citron et poivre noir Martha Stewart réunit des grains de poivre noir et des zestes de citron séchés pour une touche vive, fraîche et épicée. Idéale sur les pizzas, poissons grillés, volailles et légumes de saison.",
    "description_es": "El aceite de oliva virgen extra infusionado con limón y pimienta negra Martha Stewart une granos de pimienta negra y cáscara de limón para un toque cítrico y picante vibrante. Perfecto para pescados, pollos asados, ensaladas y pizzas.",
    "features": "Featuring: Extra-virgin olive oil, black peppercorns, dried lemon peel and de arbol peppers",
    "features_fr": "Caractéristiques : Huile d'olive extra vierge, grains de poivre noir, zeste de citron séché et piments de arbol",
    "features_es": "Características: Aceite de oliva virgen extra, granos de pimienta negra, cáscara de limón deshidratada y chiles de árbol",
    "gallery": [],
    "ingredients": "Ingredients: Extra-virgin olive oil, black peppercorns, dried lemon peel, de arbol peppers, natural flavorings (liquid lemon flavor).",
    "ingredients_fr": "Ingrédients : Huile d'olive extra vierge, grains de poivre noir, zeste de citron séché, piments de arbol, arômes naturels de citron.",
    "ingredients_es": "Ingredientes: Aceite de oliva virgen extra, granos de pimienta negra, cáscara de limón deshidratada, chiles de árbol, aromas naturales de limón."
  },
  {
    "id": 6,
    "title": "Fig Oregano Honey Drizzle",
    "title_fr": "Filet de Miel à la Figue et à l'Origan",
    "title_es": "Miel para Rociar con Higo y Orégano",
    "category": "Honeys",
    "category_fr": "Miels gastronomiques",
    "category_es": "Mieles gastronómicas",
    "image": "Fig-Oregano-Honey-Drizzle.webp",
    "description": "Martha Stewart Fig Oregano Honey Drizzle combines raw fig honey with oregano and black pepper for a rich, subtly savory take on traditional honey. Perfect for drizzling over pizza, warm goat cheese or a fresh salad, it also pairs beautifully with grilled lamb and roasted vegetables. The combination of sweet fig, fragrant oregano and black pepper adds a distinctive finishing touch to everything from appetizers to main dishes.",
    "description_fr": "Le filet de miel à la figue et à l'origan Martha Stewart unit le miel brut de figue, l'origan parfumé et le poivre noir pour une nuance délicatement sucrée-salée. Sublime sur les pizzas artisanales, fromages de chèvre chauds, agneau grillé et salades.",
    "description_es": "La miel para rociar con higo y orégano Martha Stewart combina miel pura de higo con orégano y pimienta negra para un toque agridulce sofisticado. Excelente sobre pizzas, queso de cabra tibio, cordero y verduras asadas.",
    "features": "Featuring: Raw fig honey, black pepper and dried oregano leaves",
    "features_fr": "Caractéristiques : Miel brut de figue, poivre noir et feuilles d'origan séchées",
    "features_es": "Características: Miel cruda de higo, pimienta negra y hojas de orégano seco",
    "gallery": [],
    "ingredients": "Ingredients: Raw fig honey, black pepper, dried oregano leaves.",
    "ingredients_fr": "Ingrédients : Miel brut de figue, poivre noir, feuilles d'origan séchées.",
    "ingredients_es": "Ingredientes: Miel pura de higo, pimienta negra, hojas de orégano seco."
  },
  {
    "id": 7,
    "title": "Lemon Black Pepper Honey Drizzle",
    "title_fr": "Filet de Miel au Citron et Poivre Noir",
    "title_es": "Miel para Rociar con Limón y Pimienta Negra",
    "category": "Honeys",
    "category_fr": "Miels gastronomiques",
    "category_es": "Mieles gastronómicas",
    "image": "Lemon-Black-Pepper-Honey-Drizzle.webp",
    "description": "Martha Stewart Lemon Black Pepper Honey Drizzle brings together raw lemon honey, bright citrus and black pepper for a sweet, zesty flavor with a subtle peppery finish. Drizzle it over pizza, grilled salmon or roasted vegetables, or pair it with cheese for an effortless appetizer. Its balance of sweetness, citrus and pepper makes it a versatile finishing touch for both savory and sweet dishes.",
    "description_fr": "Le filet de miel au citron et poivre noir Martha Stewart rassemble du miel brut de citronnier, des notes d'agrumes éclatantes et du poivre noir pour une harmonie douce et piquante. Rehausse le saumon grillé, les pizzas, fromages fins et desserts.",
    "description_es": "La miel para rociar con limón y pimienta negra Martha Stewart equilibra el dulzor natural de la miel con toques cítricos y el picor elegante de la pimienta negra. Ideal sobre salmón a la plancha, quesos maduros y pizzas.",
    "features": "Featuring: Raw lemon honey, lemon extract and black pepper",
    "features_fr": "Caractéristiques : Miel brut de citron, extrait naturel de citron et poivre noir",
    "features_es": "Características: Miel cruda de limón, extracto de limón y pimienta negra",
    "gallery": [],
    "ingredients": "Ingredients: Raw lemon honey, lemon extract, black pepper.",
    "ingredients_fr": "Ingrédients : Miel brut de citron, extrait de citron, poivre noir.",
    "ingredients_es": "Ingredientes: Miel pura de limón, extracto de limón, pimienta negra."
  },
  {
    "id": 8,
    "title": "Triple Chili Honey Drizzle",
    "title_fr": "Filet de Miel aux Trois Piments",
    "title_es": "Miel para Rociar con Tres Chiles",
    "category": "Honeys",
    "category_fr": "Miels gastronomiques",
    "category_es": "Mieles gastronómicas",
    "image": "MS-Honey-Triple-Chili-1.webp",
    "description": "Martha Stewart Triple Chili Honey Drizzle combines raw honey with jalapeño, habanero and cayenne peppers for a delicious balance of sweetness and heat. Drizzle it over pizza for a sweet and spicy finishing touch, pair it with grilled chicken or pork, or add it to roasted vegetables for an unexpected burst of flavor. It’s an easy way to bring a little heat—and a lot of flavor—to everyday dishes.",
    "description_fr": "Le filet de miel aux trois piments Martha Stewart associe du miel brut aux piments jalapeño, habanero et de Cayenne pour un équilibre sensationnel entre douceur dorée et intensité piquante. Parfait pour couronner vos pizzas, volailles grillées ou légumes rôtis.",
    "description_es": "La miel para rociar con tres chiles Martha Stewart combina miel pura con chiles jalapeño, habanero y cayena, creando una explosión irresistible de dulce y picante. Rocíela sobre pizzas, pollo asado o costillas.",
    "features": "Featuring: Raw honey, jalapeño pepper, habanero pepper and cayenne pepper",
    "features_fr": "Caractéristiques : Miel brut, piments jalapeño, habanero et de Cayenne",
    "features_es": "Características: Miel cruda, chiles jalapeño, habanero y cayena",
    "gallery": [],
    "ingredients": "Ingredients: Raw honey, jalapeño pepper, habanero pepper, cayenne pepper, apple cider vinegar.",
    "ingredients_fr": "Ingrédients : Miel brut, piment jalapeño, piment habanero, piment de Cayenne, vinaigre de cidre de pomme.",
    "ingredients_es": "Ingredientes: Miel cruda, chile jalapeño, chile habanero, chile cayena, vinagre de sidra de manzana."
  },
  {
    "id": 9,
    "title": "Margherita with Fresh Mozzarella Pinsa",
    "title_fr": "Pinsa Margherita à la Mozzarella Fraîche",
    "title_es": "Pinsa Margherita con Mozzarella Fresca",
    "category": "Frozen Pinsa",
    "category_fr": "Pinsa surgelée",
    "category_es": "Pinsa congelada",
    "image": "margherita-with-fresh-mozzarella-pinsa.webp",
    "description": "Martha Stewart Margherita with Fresh Mozzarella Pinsa brings together vine-ripened tomatoes, fresh mozzarella and basil on a hand-stretched, authentic Roman-style crust. Light, airy and crisp, the crust provides the perfect base for the simple, classic combination of rich tomatoes, creamy fresh mozzarella and fragrant basil. Ready in minutes, it's a fresh take on a timeless Margherita.",
    "description_fr": "La pinsa Margherita Martha Stewart réunit des tomates mûries sur pied, de la mozzarella fraîche fondante et du basilic aromatique sur une pâte romaine au levain étirée à la main. Légère, alvéolée et croustillante, prête en quelques minutes au four.",
    "description_es": "La pinsa Margherita Martha Stewart reúne tomates madurados al sol, mozzarella fresca cremosa y albahaca fragante sobre una base artesanal romana estirada a mano. Crujiente, esponjosa y lista en minutos para disfrutar.",
    "features": "Featuring: Vine-ripened tomatoes, fresh mozzarella and basil",
    "features_fr": "Caractéristiques : Tomates mûries sur pied, mozzarella fraîche et basilic",
    "features_es": "Características: Tomates madurados al sol, mozzarella fresca y albahaca",
    "gallery": [
      "margherita-with-fresh-mozzarella-pinsa-gallery-1.webp",
      "margherita-with-fresh-mozzarella-pinsa-gallery-2.webp",
      "margherita-with-fresh-mozzarella-pinsa-gallery-3.webp",
      "margherita-with-fresh-mozzarella-pinsa-gallery-4.webp",
      "margherita-with-fresh-mozzarella-pinsa-gallery-5.webp"
    ],
    "ingredients": "Ingredients: Pinsa crust (wheat flour, organic rice flour, organic fava flour, sourdough yeast, water, olive oil, salt, yeast [yeast, sorbitan monostearate, ascorbic acid]). Toppings: Fresh mozzarella slices (pasteurized milk, vinegar, microbial enzymes, salt), Mozzarella cheese (milk, modified milk ingredients, cream, salt, calcium chloride, bacterial culture, microbial enzyme), Parmesan cheese (milk, salt, lipase, microbial enzyme, bacterial culture, calcium chloride, cellulose), Basil. Tomato sauce: Diced tomatoes (tomatoes, *may contain citric acid), Crushed tomatoes, Salt, Sugar, Garlic powder, Chili flakes, Herb.\nContains: Wheat, Milk.\nMay contain: Eggs, Soy, Mustard.",
    "ingredients_fr": "Ingrédients : Pâte à pinsa (farine de blé, farine de riz biologique, farine de fève biologique, levain naturel, eau, huile d'olive, sel, levure). Garnitures : Mozzarella fraîche, mozzarella râpée, parmesan, basilic frais. Sauce tomate : Tomates concassées, sel, sucre, ail en poudre, herbes.\nContient : Blé, Lait.\nPeut contenir : Œufs, Soja, Moutarde.",
    "ingredients_es": "Ingredientes: Masa de pinsa (harina de trigo, harina de arroz orgánica, harina de haba orgánica, masa madre, agua, aceite de oliva, sal, levadura). Coberturas: Rebanadas de mozzarella fresca, queso mozzarella, queso parmesano, albahaca. Salsa de tomate: Tomates troceados, sal, azúcar, ajo en polvo, especias.\nContiene: Trigo, Leche.\nPuede contener: Huevos, Soya, Mostaza.",
    "slug": "margherita-with-fresh-mozzarella-pinsa",
    "image_ca": "",
    "image_us": "margherita-with-fresh-mozzarella-pinsa-us.webp",
    "gallery_ca": [],
    "gallery_us": [
      "margherita-with-fresh-mozzarella-pinsa-us-gallery-1.webp",
      "margherita-with-fresh-mozzarella-pinsa-us-gallery-2.webp",
      "margherita-with-fresh-mozzarella-pinsa-us-gallery-3.webp",
      "margherita-with-fresh-mozzarella-pinsa-us-gallery-4.webp",
      "margherita-with-fresh-mozzarella-pinsa-us-gallery-5.webp"
    ]
  },
  {
    "id": 10,
    "title": "Margherita with Fresh Mozzarella Pizza",
    "title_fr": "Pizza Margherita à la Mozzarella Fraîche",
    "title_es": "Pizza Margherita con Mozzarella Fresca",
    "category": "Frozen Pizza",
    "category_fr": "Pizza surgelée",
    "category_es": "Pizza congelada",
    "image": "Margherita-with-Fresh-Mozzarella-Frozen-Pizza.webp",
    "description": "Martha Stewart Margherita with Fresh Mozzarella Pizza brings together vine-ripened tomatoes, fresh mozzarella and basil on a hand-stretched, stone-baked crust. Simple, classic ingredients come together for a pizzeria-inspired Margherita with a crisp, airy crust and rich tomato flavor. Ready in minutes, it's an effortless way to enjoy a restaurant-quality pizza at home.",
    "description_fr": "La pizza Margherita Martha Stewart sublime des tomates mûries sur pied, de la mozzarella fraîche fondante et du basilic doux sur une pâte artisanale cuite sur pierre. Une texture croustillante et une saveur digne des meilleures pizzerias.",
    "description_es": "La pizza Margherita Martha Stewart ofrece el sabor clásico y puro de Italia: tomates madurados, mozzarella fresca y albahaca sobre una masa crujiente horneada a la piedra. Calidad de restaurante lista en minutos.",
    "features": "Featuring: Vine-ripened tomatoes, fresh mozzarella and basil",
    "features_fr": "Caractéristiques : Tomates mûries sur pied, mozzarella fraîche et basilic",
    "features_es": "Características: Tomates madurados al sol, mozzarella fresca y albahaca",
    "gallery": [],
    "ingredients": "Ingredients: Wheat flour, water, fresh mozzarella, tomato sauce, basil, parmesan cheese, olive oil, salt, yeast.\nContains: Wheat, Milk.",
    "ingredients_fr": "Ingrédients : Farine de blé, eau, mozzarella fraîche, sauce tomate, basilic, parmesan, huile d'olive, sel, levure.\nContient : Blé, Lait.",
    "ingredients_es": "Ingredientes: Harina de trigo, agua, mozzarella fresca, salsa de tomate, albahaca, queso parmesano, aceite de oliva, sal, levadura.\nContiene: Trigo, Leche."
  },
  {
    "id": 11,
    "title": "Roasted Garlic Pizza Sauce (375g)",
    "title_fr": "Sauce à Pizza à l'Ail Rôti (375g)",
    "title_es": "Salsa para Pizza con Ajo Asado (375g)",
    "category": "Pizza Sauce",
    "category_fr": "Sauces à pizza",
    "category_es": "Salsas para pizza",
    "image": "Roasted-Garlic-Pizza-Sauce-375ml.webp",
    "description": "Martha Stewart Roasted Garlic Pizza Sauce combines vine-ripened crushed tomatoes with roasted garlic, extra virgin olive oil, oregano, basil and black pepper for a rich, savory flavor. Spread it over pizza dough and pair with mushrooms, onions, mozzarella or your favorite toppings, or use it as a flavorful sauce for pasta and other Italian-inspired dishes. The roasted garlic adds an extra layer of depth to every bite.",
    "description_fr": "La sauce à pizza à l'ail rôti Martha Stewart marie des tomates broyées mûries sur pied à de l'ail rôti savoureux, de l'huile d'olive extra vierge, de l'origan et du basilic. Idéale pour napper pâtes à pizza et plats mijotés.",
    "description_es": "La salsa para pizza con ajo asado Martha Stewart combina tomates madurados triturados con ajo asado dulce, aceite de oliva virgen extra, orégano y albahaca. Aporta profundidad aromática a cualquier receta.",
    "features": "Featuring: Vine-ripened crushed tomatoes, roasted garlic, extra virgin olive oil, oregano and basil",
    "features_fr": "Caractéristiques : Tomates broyées mûries sur pied, ail rôti, huile d'olive extra vierge, origan et basilic",
    "features_es": "Características: Tomates triturados madurados, ajo asado, aceite de oliva virgen extra, orégano y albahaca",
    "gallery": [],
    "ingredients": "Ingredients: Vine-ripened crushed tomatoes, water, roasted garlic, extra-virgin olive oil, sea salt, oregano, basil, black pepper.",
    "ingredients_fr": "Ingrédients : Tomates broyées mûries sur pied, eau, ail rôti, huile d'olive extra vierge, sel de mer, origan, basilic, poivre noir.",
    "ingredients_es": "Ingredientes: Tomates triturados madurados al sol, agua, ajo asado, aceite de oliva virgen extra, sal marina, orégano, albahaca, pimienta negra."
  },
  {
    "id": 12,
    "title": "Roasted Garlic Pizza Sauce (680g)",
    "title_fr": "Sauce à Pizza à l'Ail Rôti (680g)",
    "title_es": "Salsa para Pizza con Ajo Asado (680g)",
    "category": "Pizza Sauce",
    "category_fr": "Sauces à pizza",
    "category_es": "Salsas para pizza",
    "image": "Roasted-Garlic-Pizza-Sauce-680ml.webp",
    "description": "Martha Stewart Roasted Garlic Pizza Sauce combines vine-ripened crushed tomatoes with roasted garlic, extra virgin olive oil, oregano, basil and black pepper for a rich, savory flavor. Spread it over pizza dough and pair with mushrooms, onions, mozzarella or your favorite toppings, or use it as a flavorful sauce for pasta and other Italian-inspired dishes. The roasted garlic adds an extra layer of depth to every bite.",
    "description_fr": "Grand format 680g. La sauce à pizza à l'ail rôti Martha Stewart sublime vos créations maison avec des tomates cueillies à maturité, de l'ail doucement rôti, de l'origan et de l'huile d'olive extra vierge.",
    "description_es": "Formato familiar 680g. La salsa para pizza con ajo asado Martha Stewart realza masas de pizza y pastas con tomates seleccionados, ajo confitado y hierbas aromáticas finas.",
    "features": "Featuring: Vine-ripened crushed tomatoes, roasted garlic, extra virgin olive oil, oregano and basil",
    "features_fr": "Caractéristiques : Tomates broyées mûries sur pied, ail rôti, huile d'olive extra vierge, origan et basilic",
    "features_es": "Características: Tomates triturados madurados, ajo asado, aceite de oliva virgen extra, orégano y albahaca",
    "gallery": [],
    "ingredients": "Ingredients: Vine-ripened crushed tomatoes, water, roasted garlic, extra-virgin olive oil, sea salt, oregano, basil, black pepper.",
    "ingredients_fr": "Ingrédients : Tomates broyées mûries sur pied, eau, ail rôti, huile d'olive extra vierge, sel de mer, origan, basilic, poivre noir.",
    "ingredients_es": "Ingredientes: Tomates triturados madurados al sol, agua, ajo asado, aceite de oliva virgen extra, sal marina, orégano, albahaca, pimienta negra."
  },
  {
    "id": 13,
    "title": "Spicy Pizza Sauce (375g)",
    "title_fr": "Sauce à Pizza Épicée (375g)",
    "title_es": "Salsa para Pizza Picante (375g)",
    "category": "Pizza Sauce",
    "category_fr": "Sauces à pizza",
    "category_es": "Salsas para pizza",
    "image": "Spicy-Pizza-Sauce-375ml.webp",
    "description": "Martha Stewart Spicy Pizza Sauce combines vine-ripened crushed tomatoes, extra virgin olive oil, garlic, oregano and basil with crushed chilies for a flavorful kick of heat. Use it as the base for a spicy pizza topped with Italian sausage, mozzarella and your favorite vegetables, or spoon it over polenta for a quick and flavorful meal. It's an easy way to add bold tomato flavor and a touch of heat to your favorite dishes.",
    "description_fr": "La sauce à pizza épicée Martha Stewart apporte une pointe de piquant grâce à des piments rouges broyés, associés à des tomates gorgées de soleil, de l'ail et de l'huile d'olive extra vierge.",
    "description_es": "La salsa para pizza picante Martha Stewart ofrece un toque vibrante de picor con hojuelas de chile trituradas, tomates madurados, ajo y orégano italiano. Perfecta para pizzas con carácter.",
    "features": "Featuring: Vine-ripened crushed tomatoes, crushed chilies, extra virgin olive oil, garlic and basil",
    "features_fr": "Caractéristiques : Tomates broyées, piments concassés, huile d'olive extra vierge, ail et basilic",
    "features_es": "Características: Tomates madurados triturados, chiles secos, aceite de oliva virgen extra, ajo y albahaca",
    "gallery": [],
    "ingredients": "Ingredients: Vine-ripened crushed tomatoes, water, extra-virgin olive oil, chopped garlic, sea salt, crushed chilies, oregano, basil, black pepper.",
    "ingredients_fr": "Ingrédients : Tomates broyées mûries sur pied, eau, huile d'olive extra vierge, ail haché, sel de mer, piments concassés, origan, basilic, poivre noir.",
    "ingredients_es": "Ingredientes: Tomates triturados, agua, aceite de oliva virgen extra, ajo picado, sal marina, chiles triturados, orégano, albahaca, pimienta negra."
  },
  {
    "id": 14,
    "title": "Spicy Pizza Sauce (680g)",
    "title_fr": "Sauce à Pizza Épicée (680g)",
    "title_es": "Salsa para Pizza Picante (680g)",
    "category": "Pizza Sauce",
    "category_fr": "Sauces à pizza",
    "category_es": "Salsas para pizza",
    "image": "Spicy-Pizza-Sauce-680ml.webp",
    "description": "Martha Stewart Spicy Pizza Sauce combines vine-ripened crushed tomatoes, extra virgin olive oil, garlic, oregano and basil with crushed chilies for a flavorful kick of heat. Use it as the base for a spicy pizza topped with Italian sausage, mozzarella and your favorite vegetables, or spoon it over polenta for a quick and flavorful meal. It's an easy way to add bold tomato flavor and a touch of heat to your favorite dishes.",
    "description_fr": "Grand format 680g. La sauce à pizza épicée Martha Stewart sublime les pizzas à la saucisse italienne et les calzones avec son savoureux mélange de piments concassés et tomates mûries au soleil.",
    "description_es": "Formato familiar 680g. La salsa para pizza picante Martha Stewart agrega audacia y calor suave con tomates maduros, aceite de oliva virgen extra y chiles finamente picados.",
    "features": "Featuring: Vine-ripened crushed tomatoes, crushed chilies, extra virgin olive oil, garlic and basil",
    "features_fr": "Caractéristiques : Tomates broyées, piments concassés, huile d'olive extra vierge, ail et basilic",
    "features_es": "Características: Tomates madurados triturados, chiles secos, aceite de oliva virgen extra, ajo y albahaca",
    "gallery": [],
    "ingredients": "Ingredients: Vine-ripened crushed tomatoes, water, extra-virgin olive oil, chopped garlic, sea salt, crushed chilies, oregano, basil, black pepper.",
    "ingredients_fr": "Ingrédients : Tomates broyées mûries sur pied, eau, huile d'olive extra vierge, ail haché, sel de mer, piments concassés, origan, basilic, poivre noir.",
    "ingredients_es": "Ingredientes: Tomates triturados, agua, aceite de oliva virgen extra, ajo picado, sal marina, chiles triturados, orégano, albahaca, pimienta negra."
  },
  {
    "id": 15,
    "title": "Traditional Pizza Sauce (375g)",
    "title_fr": "Sauce à Pizza Traditionnelle (375g)",
    "title_es": "Salsa para Pizza Tradicional (375g)",
    "category": "Pizza Sauce",
    "category_fr": "Sauces à pizza",
    "category_es": "Salsas para pizza",
    "image": "Traditional-Pizza-Sauce-375ml.webp",
    "description": "Martha Stewart Traditional Pizza Sauce combines vine-ripened crushed tomatoes with extra virgin olive oil, garlic, oregano, basil and black pepper for a classic, well-balanced flavor. Spread it over your favorite pizza dough and top with fresh mozzarella and basil for a simple, delicious pizza, or use it to bring rich tomato flavor to chicken parmesan, baked pasta and other Italian-inspired dishes.",
    "description_fr": "La sauce à pizza traditionnelle Martha Stewart associe des tomates mûries sur pied, de l'huile d'olive extra vierge, de l'ail, de l'origan et du basilic pour un goût italien authentique et équilibré.",
    "description_es": "La salsa para pizza tradicional Martha Stewart reúne tomates maduros triturados con aceite de oliva virgen extra, ajo, albahaca y orégano para un sabor clásico y armonioso.",
    "features": "Featuring: Vine-ripened crushed tomatoes, extra virgin olive oil, garlic, oregano and basil",
    "features_fr": "Caractéristiques : Tomates broyées, huile d'olive extra vierge, ail, origan et basilic",
    "features_es": "Características: Tomates madurados al sol, aceite de oliva virgen extra, ajo, orégano y albahaca",
    "gallery": [],
    "ingredients": "Ingredients: Vine-ripened crushed tomatoes, water, extra-virgin olive oil, chopped garlic, sea salt, oregano, basil, black pepper.",
    "ingredients_fr": "Ingrédients : Tomates broyées mûries sur pied, eau, huile d'olive extra vierge, ail haché, sel de mer, origan, basilic, poivre noir.",
    "ingredients_es": "Ingredientes: Tomates triturados madurados, agua, aceite de oliva virgen extra, ajo picado, sal marina, orégano, albahaca, pimienta negra."
  },
  {
    "id": 16,
    "title": "Traditional Pizza Sauce (680g)",
    "title_fr": "Sauce à Pizza Traditionnelle (680g)",
    "title_es": "Salsa para Pizza Tradicional (680g)",
    "category": "Pizza Sauce",
    "category_fr": "Sauces à pizza",
    "category_es": "Salsas para pizza",
    "image": "Traditional-Pizza-Sauce-680ml.webp",
    "description": "Martha Stewart Traditional Pizza Sauce combines vine-ripened crushed tomatoes with extra virgin olive oil, garlic, oregano, basil and black pepper for a classic, well-balanced flavor. Spread it over your favorite pizza dough and top with fresh mozzarella and basil for a simple, delicious pizza, or use it to bring rich tomato flavor to chicken parmesan, baked pasta and other Italian-inspired dishes.",
    "description_fr": "Grand format 680g. La sauce à pizza traditionnelle Martha Stewart offre une texture veloutée et des saveurs italiennes pures pour toute la famille, idéale pour pizzas et pâtes au four.",
    "description_es": "Formato familiar 680g. La salsa para pizza tradicional Martha Stewart proporciona un sabor clásico inconfundible con ingredientes puros y naturales para toda la familia.",
    "features": "Featuring: Vine-ripened crushed tomatoes, extra virgin olive oil, garlic, oregano and basil",
    "features_fr": "Caractéristiques : Tomates broyées, huile d'olive extra vierge, ail, origan et basilic",
    "features_es": "Características: Tomates madurados al sol, aceite de oliva virgen extra, ajo, orégano y albahaca",
    "gallery": [],
    "ingredients": "Ingredients: Vine-ripened crushed tomatoes, water, extra-virgin olive oil, chopped garlic, sea salt, oregano, basil, black pepper.",
    "ingredients_fr": "Ingrédients : Tomates broyées mûries sur pied, eau, huile d'olive extra vierge, ail haché, sel de mer, origan, basilic, poivre noir.",
    "ingredients_es": "Ingredientes: Tomates triturados madurados, agua, aceite de oliva virgen extra, ajo picado, sal marina, orégano, albahaca, pimienta negra."
  },
  {
    "id": 17,
    "title": "Garden Herb Seasoning",
    "title_fr": "Assaisonnement aux Herbes du Jardin",
    "title_es": "Sazonador de Hierbas del Huerto",
    "category": "Seasoning",
    "category_fr": "Assaisonnements",
    "category_es": "Sazonadores y especias",
    "image": "Garden-Herb-Seasoning.webp",
    "description": "Martha Stewart Garden Herb Seasoning is a bright, savory blend of sea salt, herbs, onion, garlic, black pepper and lemon. Sprinkle it over oven-baked pizza for an easy finishing touch, season roasted vegetables, chicken or potatoes, or mix it with mayonnaise and sour cream for a quick herb dip. Its fresh, versatile flavor makes it an effortless addition to everyday cooking.",
    "description_fr": "L'assaisonnement aux herbes du jardin Martha Stewart est un mélange vivifiant de sel de mer, aneth, persil, ciboulette, ail et zeste de citron. Parfait sur les légumes rôtis, volailles, pommes de terre et trempettes.",
    "description_es": "El sazonador de hierbas del huerto Martha Stewart es una mezcla fresca y aromática de sal marina, hierbas finas, cebolla, ajo, pimienta negra y toque de limón. Excelente para vegetales asados y carnes.",
    "features": "Featuring: Sea salt, dill, parsley, chives, garlic and lemon peel",
    "features_fr": "Caractéristiques : Sel de mer, aneth, persil, ciboulette, ail et zeste de citron",
    "features_es": "Características: Sal marina, eneldo, perejil, cebollino, ajo y ralladura de limón",
    "gallery": [],
    "ingredients": "Ingredients: Sea salt, herbs (dill weed, parsley, chives), dehydrated vegetables (onion, garlic), black pepper, lemon juice powder, dehydrated lemon peel, natural lemon flavor, citric acid.",
    "ingredients_fr": "Ingrédients : Sel de mer, herbes (aneth, persil, ciboulette), légumes déshydratés (oignon, ail), poivre noir, jus de citron en poudre, zeste de citron déshydraté, arôme naturel de citron, acide citrique.",
    "ingredients_es": "Ingredientes: Sal marina, hierbas aromáticas (eneldo, perejil, cebollino), verduras deshidratadas (cebolla, ajo), pimienta negra, jugo de limón en polvo, cáscara de limón deshidratada, aroma natural de limón, ácido cítrico."
  },
  {
    "id": 18,
    "title": "Mediterranean Tomato Seasoning",
    "title_fr": "Assaisonnement Méditerranéen à la Tomate",
    "title_es": "Sazonador Mediterráneo con Tomate",
    "category": "Seasoning",
    "category_fr": "Assaisonnements",
    "category_es": "Sazonadores y especias",
    "image": "Mediterranean-Tomato-Seasoning.webp",
    "description": "Martha Stewart Mediterranean Tomato Seasoning combines tomato, red bell pepper, basil, thyme, garlic, onion and black pepper for a savory, herb-forward blend inspired by Mediterranean flavors. Use it as a finishing touch for oven-baked pizza, sprinkle it over roasted vegetables or chicken, or mix it into a simple vinaigrette for fresh mozzarella or bocconcini. It's an easy way to add rich tomato and herb flavor to everyday dishes.",
    "description_fr": "L'assaisonnement méditerranéen à la tomate Martha Stewart réunit tomate séchée, poivron rouge, basilic, thym, ail et poivre noir. Inspiré des rivages ensoleillés pour sublimer pizzas, salades de bocconcini et grillades.",
    "description_es": "El sazonador mediterráneo con tomate Martha Stewart combina tomate deshidratado, pimiento rojo, albahaca, tomillo y ajo para un toque soleado irresistible. Ideal para quesos frescos, ensaladas y pizzas.",
    "features": "Featuring: Dehydrated tomato, red bell pepper, basil, thyme, garlic and black pepper",
    "features_fr": "Caractéristiques : Tomate déshydratée, poivron rouge, basilic, thym, ail et poivre noir",
    "features_es": "Características: Tomate deshidratado, pimiento rojo, albahaca, tomillo, ajo y pimienta negra",
    "gallery": [],
    "ingredients": "Ingredients: Dehydrated vegetables (tomato, onion, garlic, red bell pepper), sea salt, herbs (basil, thyme), black pepper, olive oil, silicon dioxide (anti-caking agent), natural lemon flavor.",
    "ingredients_fr": "Ingrédients : Légumes déshydratés (tomate, oignon, ail, poivron rouge), sel de mer, herbes (basilic, thym), poivre noir, huile d'olive, arôme naturel de citron.",
    "ingredients_es": "Ingredientes: Verduras deshidratadas (tomate, cebolla, ajo, pimiento rojo), sal marina, hierbas (albahaca, tomillo), pimienta negra, aceite de oliva, aroma natural de limón."
  },
  {
    "id": 19,
    "title": "Sweet Italian Seasoning",
    "title_fr": "Assaisonnement Doux à l'Italienne",
    "title_es": "Sazonador Italiano Dulce",
    "category": "Seasoning",
    "category_fr": "Assaisonnements",
    "category_es": "Sazonadores y especias",
    "image": "Sweet-Italian-Seasoning.webp",
    "description": "Martha Stewart Sweet Italian Seasoning brings together sea salt, garlic, onion, red bell pepper, fennel seed and rosemary for a savory, aromatic blend with a subtle touch of sweetness. Sprinkle it over oven-baked pizza, use it to season pork or chicken, or add it to roasted vegetables and potatoes. Its classic Italian-inspired flavors make it a versatile pantry staple for adding depth to everyday dishes.",
    "description_fr": "L'assaisonnement doux à l'italienne Martha Stewart associe sel de mer, ail, oignon, graines de fenouil et romarin avec une subtile touche sucrée. Indispensable pour assaisonner porc, volailles, pommes de terre et pâtes.",
    "description_es": "El sazonador italiano dulce Martha Stewart une sal marina, ajo, cebolla, pimiento rojo, semillas de hinojo y romero con un toque sutilmente dulce. Un condimento versátil para aves, carnes y pastas.",
    "features": "Featuring: Sea salt, garlic, onion, red bell pepper, fennel seed and rosemary",
    "features_fr": "Caractéristiques : Sel de mer, ail, oignon, poivron rouge, graines de fenouil et romarin",
    "features_es": "Características: Sal marina, ajo, cebolla, pimiento rojo, semillas de hinojo y romero",
    "gallery": [],
    "ingredients": "Ingredients: Sea salt, dehydrated vegetables (garlic, onion, red bell pepper), fennel seed, rosemary, olive oil.",
    "ingredients_fr": "Ingrédients : Sel de mer, légumes déshydratés (ail, oignon, poivron rouge), graines de fenouil, romarin, huile d'olive.",
    "ingredients_es": "Ingredientes: Sal marina, verduras deshidratadas (ajo, cebolla, pimiento rojo), semillas de hinojo, romero, aceite de oliva."
  },
  {
    "id": 20,
    "title": "Triple Pepper Mix Seasoning",
    "title_fr": "Mélange d'Épices aux Trois Poivres",
    "title_es": "Mezcla de Condimentos Tres Pimientas",
    "category": "Seasoning",
    "category_fr": "Assaisonnements",
    "category_es": "Sazonadores y especias",
    "image": "Triple-Pepper-Mix-Seasoning.webp",
    "description": "Martha Stewart Triple Pepper Mix Seasoning combines sea salt, black pepper, gochugaru chili flakes and chili pepper flakes for a bold blend with a flavorful kick of heat. Use it as a finishing touch for oven-baked pizza, season steak or pork before cooking, or sprinkle it over roasted vegetables and potatoes. The combination of peppers adds warmth and depth without overpowering your favorite dishes.",
    "description_fr": "L'assaisonnement aux trois poivres Martha Stewart réunit sel de mer, poivre noir, flocons de piment gochugaru et piments rouges concassés. Une chaleur équilibrée qui sublime viandes rouges, steaks et légumes sautés.",
    "description_es": "El sazonador tres pimientas Martha Stewart combina sal marina, pimienta negra, hojuelas de chile gochugaru y chile rojo. Aporta calidez y profundidad aromática a bistecs, hamburguesas y papas asadas.",
    "features": "Featuring: Sea salt, black pepper, gochugaru chili flakes and chili pepper flakes",
    "features_fr": "Caractéristiques : Sel de mer, poivre noir, flocons de piment gochugaru et piments concassés",
    "features_es": "Características: Sal marina, pimienta negra, hojuelas de chile gochugaru y hojuelas de chile",
    "gallery": [],
    "ingredients": "Ingredients: Sea salt, black pepper, gochugaru chili flakes, chili pepper flakes.",
    "ingredients_fr": "Ingrédients : Sel de mer, poivre noir, flocons de piment gochugaru, flocons de piment chili.",
    "ingredients_es": "Ingredientes: Sal marina, pimienta negra, hojuelas de chile gochugaru, hojuelas de chile rojo."
  },
  {
    "id": 21,
    "title": "Neapolitan Style Dough Mix",
    "title_fr": "Mélange à Pâte à Pizza Style Napolitain",
    "title_es": "Mezcla para Masa de Pizza Estilo Napolitano",
    "category": "Pizza Flour",
    "category_fr": "Farines à pizza",
    "category_es": "Harinas para pizza",
    "image": "Neapolitan-Style-Pizza-Dough-Mix.webp",
    "description": "Martha Stewart Neapolitan Style 00 Pizza Dough Mix is crafted with premium Italian 00 flour to create the light, airy crust with a delicate crisp that defines classic Neapolitan-style pizza. Stretch it thin, top with crushed tomatoes and fresh mozzarella, and bake at high heat for a restaurant-inspired Margherita at home. Designed for high-temperature baking, this flour mix gives you pizzeria-quality results in your home oven.",
    "description_fr": "Le mélange pour pâte à pizza style napolitain Martha Stewart est élaboré à partir de farine italienne Tipo 00 de qualité supérieure. Permet d'obtenir une croûte gonflée, légère et délicatement alvéolée à haute température.",
    "description_es": "La mezcla para masa de pizza estilo napolitano Martha Stewart está formulada con harina italiana Tipo 00 de primera calidad para una masa elástica, ligera y de bordes aireados (cornicione) como en Nápoles.",
    "features": "Featuring: Premium Italian 00 flour for high-heat pizza baking",
    "features_fr": "Caractéristiques : Farine italienne Tipo 00 supérieure pour cuisson à haute température",
    "features_es": "Características: Harina italiana Tipo 00 premium para horneado a alta temperatura",
    "gallery": [],
    "ingredients": "Made with: Premium Italian 00 flour.",
    "ingredients_fr": "Composé de : Farine italienne Tipo 00 de qualité supérieure.",
    "ingredients_es": "Elaborado con: Harina italiana Tipo 00 de primera calidad."
  },
  {
    "id": 22,
    "title": "Neapolitan Style Pizza Dough Balls",
    "title_fr": "Boules de Pâte à Pizza Style Napolitain",
    "title_es": "Bolas de Masa para Pizza Estilo Napolitano",
    "category": "Frozen Pizza Dough",
    "category_fr": "Pâtes à pizza surgelées",
    "category_es": "Masa de pizza congelada",
    "image": "Neapolitan-Style-Frozen-Pizza-Dough.webp",
    "description": "Martha Stewart Neapolitan Style Pizza Dough Balls make it easy to create authentic, pizzeria-inspired pizza at home with a light, airy crust and beautifully crisp exterior. Simply thaw, stretch and top with your favorite sauce, cheese and toppings. Perfect for a classic Margherita or your own creation, each ready-to-use dough ball takes the work out of making dough from scratch while delivering delicious homemade results.",
    "description_fr": "Les boules de pâte à pizza style napolitain Martha Stewart facilitent la préparation de véritables pizzas de chef à la maison. Décongelez, étirez et garnissez pour une croûte aérée et croustillante.",
    "description_es": "Las bolas de masa para pizza estilo napolitano Martha Stewart permiten preparar pizzas artesanales en casa sin complicaciones. Descongele, extienda y hornee para una masa suave, ligera y crujiente.",
    "features": "2 ready-to-use pizza dough balls",
    "features_fr": "2 boules de pâte à pizza prêtes à l'emploi",
    "features_es": "2 bolas de masa para pizza listas para usar",
    "gallery": [],
    "ingredients": "Ingredients: Enriched wheat flour, water, sourdough starter, sea salt, extra virgin olive oil, yeast.\nContains: Wheat.",
    "ingredients_fr": "Ingrédients : Farine de blé enrichie, eau, levain naturel, sel de mer, huile d'olive extra vierge, levure.\nContient : Blé.",
    "ingredients_es": "Ingredientes: Harina de trigo enriquecida, agua, masa madre natural, sal marina, aceite de oliva virgen extra, levadura.\nContiene: Trigo."
  },
  {
    "id": 23,
    "title": "New York Style Pizza Dough Balls",
    "title_fr": "Boules de Pâte à Pizza Style New-Yorkais",
    "title_es": "Bolas de Masa para Pizza Estilo Nueva York",
    "category": "Frozen Pizza Dough",
    "category_fr": "Pâtes à pizza surgelées",
    "category_es": "Masa de pizza congelada",
    "image": "New-York-Style-Frozen-Pizza-Dough.webp",
    "description": "Martha Stewart New York Style Pizza Dough Balls make it easy to create classic New York-style pizza at home with a thin, crisp crust and satisfyingly chewy texture. Simply thaw, stretch and add your favorite sauce, cheese and toppings for an effortless homemade pizza night. Each ready-to-use dough ball gives you the foundation for a generously sized, pizzeria-inspired pizza without the time and preparation of making dough from scratch.",
    "description_fr": "Les boules de pâte style new-yorkais Martha Stewart vous offrent la pâte fine et croustillante emblématique de New York. Étirez facilement une grande pizza généreuse prête à cuire.",
    "description_es": "Las bolas de masa estilo Nueva York Martha Stewart son ideales para hornear pizzas grandes con la masa delgada, crujiente y flexible típica de las pizzerías neoyorquinas.",
    "features": "2 ready-to-use pizza dough balls",
    "features_fr": "2 boules de pâte à pizza prêtes à l'emploi",
    "features_es": "2 bolas de masa para pizza listas para usar",
    "gallery": [],
    "ingredients": "Ingredients: Enriched unbleached wheat flour, water, olive oil, cane sugar, sea salt, yeast.\nContains: Wheat.",
    "ingredients_fr": "Ingrédients : Farine de blé non blanchie enrichie, eau, huile d'olive, sucre de canne, sel de mer, levure.\nContient : Blé.",
    "ingredients_es": "Ingredientes: Harina de trigo enriquecida sin blanquear, agua, aceite de oliva, azúcar de caña, sal marina, levadura.\nContiene: Trigo."
  },
  {
    "id": 24,
    "title": "New York Style Dough Mix",
    "title_fr": "Mélange à Pâte à Pizza Style New-Yorkais",
    "title_es": "Mezcla para Masa de Pizza Estilo Nueva York",
    "category": "Pizza Flour",
    "category_fr": "Farines à pizza",
    "category_es": "Harinas para pizza",
    "image": "New-York-Style-Pizza-Dough-Mix.webp",
    "description": "Martha Stewart New York Style Pizza Dough Mix is crafted with premium Italian flour to create the thin, crisp yet chewy crust that defines a classic New York-style pizza. Stretch it into a generously sized pizza and top with sauce, mozzarella, pepperoni or your favorite toppings. Designed for making pizzeria-style pizza at home, this mix delivers a flavorful crust that's sturdy enough to hold your toppings while remaining satisfyingly chewy.",
    "description_fr": "Le mélange pour pâte style new-yorkais Martha Stewart est préparé avec des farines choisies pour obtenir une croûte fine, dorée et moelleuse, solide pour accueillir toutes vos garnitures favorites.",
    "description_es": "La mezcla para masa estilo Nueva York Martha Stewart permite lograr la clásica corteza delgada y ligeramente elástica que sostiene generosas cantidades de queso y pepperoni.",
    "features": "Featuring: Premium Italian flour for authentic New York-style pizza crust",
    "features_fr": "Caractéristiques : Farine italienne de qualité supérieure pour croûte new-yorkaise authentique",
    "features_es": "Características: Harina italiana de primera calidad para auténtica masa estilo Nueva York",
    "gallery": [],
    "ingredients": "Made with: Premium Italian flour.",
    "ingredients_fr": "Composé de : Farine italienne de qualité supérieure.",
    "ingredients_es": "Elaborado con: Harina italiana de primera calidad."
  },
  {
    "id": 25,
    "title": "Pepperoni and Hot Pickled Peppers Pinsa",
    "title_fr": "Pinsa au Pepperoni et Piments Marinés Piquants",
    "title_es": "Pinsa de Pepperoni y Chiles Encurtidos Picantes",
    "category": "Frozen Pinsa",
    "category_fr": "Pinsa surgelée",
    "category_es": "Pinsa congelada",
    "image": "pepperoni-and-hot-pickled-peppers-pinsa.webp",
    "description": "Martha Stewart Pepperoni and Hot Pickled Peppers Pinsa combines savory pepperoni with tangy hot pickled peppers, mozzarella and Parmesan on a hand-stretched, authentic Roman-style crust. Light and airy with a crisp exterior, the crust complements the richness of the pepperoni and cheese while hot pickled peppers add a bright, spicy kick. It's a bold twist on classic pepperoni, ready to enjoy at home in minutes.",
    "description_fr": "La pinsa au pepperoni et piments marinés piquants Martha Stewart associe du pepperoni savoureux, des piments marinés acidulés, de la mozzarella et du parmesan sur une pâte romaine au levain croustillante. Un délice audacieux prêt en quelques minutes.",
    "description_es": "La pinsa de pepperoni y chiles encurtidos picantes Martha Stewart equilibra el pepperoni especiado con chiles picantes y quesos fundidos sobre una masa romana ligera y crujiente.",
    "features": "Featuring: Pepperoni, hot pickled peppers, mozzarella and Parmesan",
    "features_fr": "Caractéristiques : Pepperoni, piments marinés piquants, mozzarella et parmesan",
    "features_es": "Características: Pepperoni, chiles encurtidos picantes, mozzarella y parmesano",
    "gallery": [
      "pepperoni-and-hot-pickled-peppers-pinsa-gallery-1.webp",
      "pepperoni-and-hot-pickled-peppers-pinsa-gallery-2.webp",
      "pepperoni-and-hot-pickled-peppers-pinsa-gallery-3.webp",
      "pepperoni-and-hot-pickled-peppers-pinsa-gallery-4.webp",
      "pepperoni-and-hot-pickled-peppers-pinsa-gallery-5.webp"
    ],
    "ingredients": "Ingredients: Pinsa crust (wheat flour, organic rice flour, organic fava flour, sourdough yeast, water, olive oil, salt, yeast [yeast, sorbitan monostearate, ascorbic acid]). Toppings: Mozzarella cheese (milk, modified milk ingredients, cream, salt, calcium chloride, bacterial culture, microbial enzyme), Pepperoni (pork, salt, pork stock, dextrose, spice extracts, lactic acid starter culture, sodium erythorbate, natural smoke flavor, dehydrated garlic, sodium nitrite, citric acid, smoke), Red and yellow hot pickled peppers (peppers, water, salt, acetic acid, calcium chloride, sodium benzoate, sodium metabisulfite, turmeric), Parmesan cheese (milk, salt, lipase, microbial enzyme, bacterial culture, calcium chloride, cellulose). Tomato sauce: Diced tomatoes (tomatoes, *may contain citric acid), Crushed tomatoes, Salt, Sugar, Garlic powder, Chili flakes, Herb.\nContains: Wheat, Milk.\nMay contain: Eggs, Soy, Mustard.",
    "ingredients_fr": "Ingrédients : Pâte à pinsa (farine de blé, farine de riz bio, farine de fève bio, levain, eau, huile d'olive, sel, levure). Garnitures : Mozzarella, pepperoni de porc, piments forts marinés rouges et jaunes, parmesan. Sauce tomate aux herbes.\nContient : Blé, Lait.\nPeut contenir : Œufs, Soja, Moutarde.",
    "ingredients_es": "Ingredientes: Masa de pinsa (harina de trigo, harina de arroz orgánica, harina de haba orgánica, masa madre, agua, aceite de oliva, sal, levadura). Coberturas: Queso mozzarella, pepperoni de cerdo, chiles encurtidos picantes rojos y amarillos, queso parmesano. Salsa de tomate sazonada.\nContiene: Trigo, Leche.\nPuede contener: Huevos, Soya, Mostaza.",
    "slug": "pepperoni-and-hot-pickled-peppers-pinsa",
    "image_ca": "",
    "image_us": "pepperoni-and-hot-pickled-peppers-pinsa-us.webp",
    "gallery_ca": [],
    "gallery_us": [
      "pepperoni-and-hot-pickled-peppers-pinsa-us-gallery-1.webp",
      "pepperoni-and-hot-pickled-peppers-pinsa-us-gallery-2.webp",
      "pepperoni-and-hot-pickled-peppers-pinsa-us-gallery-3.webp",
      "pepperoni-and-hot-pickled-peppers-pinsa-us-gallery-4.webp",
      "pepperoni-and-hot-pickled-peppers-pinsa-us-gallery-5.webp"
    ]
  },
  {
    "id": 26,
    "title": "Pepperoni and Hot Pickled Peppers Pizza",
    "title_fr": "Pizza au Pepperoni et Piments Marinés Piquants",
    "title_es": "Pizza de Pepperoni y Chiles Encurtidos Picantes",
    "category": "Frozen Pizza",
    "category_fr": "Pizza surgelée",
    "category_es": "Pizza congelada",
    "image": "Pepperoni-and-Hot-Pickled-Peppers-Frozen-Pizza.webp",
    "description": "Martha Stewart Pepperoni and Hot Pickled Peppers Pizza combines savory pepperoni with tangy hot pickled peppers, mozzarella and Parmesan on a hand-stretched, stone-baked crust. Bold, savory and pleasantly spicy, every bite balances rich pepperoni and melted cheese with the bright kick of pickled peppers. It's a flavorful twist on a classic pepperoni pizza, ready to bake and enjoy in minutes.",
    "description_fr": "La pizza au pepperoni et piments marinés piquants Martha Stewart offre une version relevée de la pizza classique. Cuite sur pierre, avec pepperoni croustillant, fromage fondant et piments acidulés.",
    "description_es": "La pizza de pepperoni y chiles encurtidos picantes Martha Stewart reinventa la pizza tradicional con una combinación vibrante de queso derretido, pepperoni artesanal y chiles encurtidos.",
    "features": "Featuring: Pepperoni, hot pickled peppers, mozzarella and Parmesan",
    "features_fr": "Caractéristiques : Pepperoni, piments marinés piquants, mozzarella et parmesan",
    "features_es": "Características: Pepperoni, chiles encurtidos picantes, mozzarella y parmesano",
    "gallery": [],
    "ingredients": "Ingredients: Wheat flour, water, mozzarella cheese, pepperoni, hot pickled peppers, tomato sauce, parmesan cheese, olive oil, salt, yeast.\nContains: Wheat, Milk.",
    "ingredients_fr": "Ingrédients : Farine de blé, eau, fromage mozzarella, pepperoni, piments marinés forts, sauce tomate, fromage parmesan, huile d'olive, sel, levure.\nContient : Blé, Lait.",
    "ingredients_es": "Ingredientes: Harina de trigo, agua, queso mozzarella, pepperoni, chiles picantes encurtidos, salsa de tomate, queso parmesano, aceite de oliva, sal, levadura.\nContiene: Trigo, Leche."
  },
  {
    "id": 27,
    "title": "Roasted Garlic Infused Extra Virgin Olive Oil",
    "title_fr": "Huile d'Olive Extra Vierge Infusée à l'Ail Rôti",
    "title_es": "Aceite de Oliva Virgen Extra Infusionado con Ajo Asado",
    "category": "Infused Oils",
    "category_fr": "Huiles infusées",
    "category_es": "Aceites infusionados",
    "image": "Roasted-Garlic-Infused-Extra-Virgin-Olive-Oil.webp",
    "description": "Martha Stewart Roasted Garlic Infused Extra Virgin Olive Oil brings together extra virgin olive oil with the rich, savory flavor of roasted garlic, rosemary, thyme and oregano. Fragrant and versatile, it adds delicious depth to oven-baked pizzas and is equally at home drizzled over vegetables, pasta or crusty bread. Try rubbing it over a whole chicken before roasting for a beautifully golden, flavorful finish.",
    "description_fr": "L'huile d'olive extra vierge infusée à l'ail rôti Martha Stewart marie l'huile d'olive de première pression à de l'ail rôti suave, du romarin, du thym et de l'origan. Exquise pour badigeonner volailles et arroser pizzas ou pains chauds.",
    "description_es": "El aceite de oliva virgen extra infusionado con ajo asado Martha Stewart combina aceite virgen extra con ajo dorado, romero, tomillo y orégano. Da un toque gourmet a pastas, carnes y panes rústicos.",
    "features": "Featuring: Extra-virgin olive oil, roasted garlic, rosemary, thyme and oregano",
    "features_fr": "Caractéristiques : Huile d'olive extra vierge, ail rôti, romarin, thym et origan",
    "features_es": "Características: Aceite de oliva virgen extra, ajo asado, romero, tomillo y orégano",
    "gallery": [],
    "ingredients": "Ingredients: Extra-virgin olive oil, rosemary, minced garlic, thyme, oregano, natural flavorings (liquid garlic flavor).",
    "ingredients_fr": "Ingrédients : Huile d'olive extra vierge, romarin, ail haché, thym, origan, arômes naturels d'ail.",
    "ingredients_es": "Ingredientes: Aceite de oliva virgen extra, romero, ajo picado, tomillo, orégano, aromas naturales de ajo."
  },
  {
    "id": 28,
    "title": "Sausage and Hot Honey Pinsa",
    "title_fr": "Pinsa à la Saucisse Italienne et Miel Piquant",
    "title_es": "Pinsa de Salchicha Italiana y Miel Picante",
    "category": "Frozen Pinsa",
    "category_fr": "Pinsa surgelée",
    "category_es": "Pinsa congelada",
    "image": "sausage-and-hot-honey-pinsa.webp",
    "description": "Martha Stewart Sausage and Hot Honey Pinsa combines savory Italian sausage and fresh mozzarella with hot honey on a hand-stretched, authentic Roman-style crust. The light, airy and crisp crust pairs beautifully with rich Italian sausage, creamy mozzarella and a sweet kick of heat from the hot honey. It's a bold balance of sweet and savory flavors, ready to bake and enjoy in minutes.",
    "description_fr": "La pinsa à la saucisse italienne et miel piquant Martha Stewart marie saucisse italienne assaisonnée, mozzarella fraîche et un filet de miel piquant sur une croûte romaine légère et croustillante. Une alliance sucrée-salée irrésistible.",
    "description_es": "La pinsa de salchicha italiana y miel picante Martha Stewart reúne salchicha sazonada, mozzarella cremosa y miel picante sobre una masa artesanal de masa madre crujiente.",
    "features": "Featuring: Fresh mozzarella, Italian sausage and hot honey",
    "features_fr": "Caractéristiques : Mozzarella fraîche, saucisse italienne et miel piquant",
    "features_es": "Características: Mozzarella fresca, salchicha italiana y miel picante",
    "gallery": [
      "sausage-and-hot-honey-pinsa-gallery-1.webp",
      "sausage-and-hot-honey-pinsa-gallery-2.webp",
      "sausage-and-hot-honey-pinsa-gallery-3.webp",
      "sausage-and-hot-honey-pinsa-gallery-4.webp",
      "sausage-and-hot-honey-pinsa-gallery-5.webp"
    ],
    "ingredients": "Ingredients: Pinsa crust (wheat flour, organic rice flour, organic fava flour, sourdough yeast, water, olive oil, salt, yeast), Italian sausage (pork, spices, salt), fresh mozzarella, hot honey, tomato sauce.\nContains: Wheat, Milk.",
    "ingredients_fr": "Ingrédients : Pâte à pinsa (farine de blé, farine de riz bio, farine de fève bio, levain, eau, huile d'olive, sel, levure), saucisse italienne de porc, mozzarella fraîche, miel piquant, sauce tomate.\nContient : Blé, Lait.",
    "ingredients_es": "Ingredientes: Masa de pinsa (harina de trigo, harina de arroz orgánica, harina de haba orgánica, masa madre, agua, aceite de oliva, sal, levadura), salchicha italiana de cerdo, mozzarella fresca, miel picante, salsa de tomate.\nContiene: Trigo, Leche.",
    "slug": "sausage-and-hot-honey-pinsa",
    "image_ca": "",
    "image_us": "sausage-and-hot-honey-pinsa-us.webp",
    "gallery_ca": [],
    "gallery_us": [
      "sausage-and-hot-honey-pinsa-us-gallery-1.webp",
      "sausage-and-hot-honey-pinsa-us-gallery-2.webp",
      "sausage-and-hot-honey-pinsa-us-gallery-3.webp",
      "sausage-and-hot-honey-pinsa-us-gallery-4.webp",
      "sausage-and-hot-honey-pinsa-us-gallery-5.webp"
    ]
  },
  {
    "id": 29,
    "title": "Sausage and Hot Honey Pizza",
    "title_fr": "Pizza à la Saucisse Italienne et Miel Piquant",
    "title_es": "Pizza de Salchicha Italiana y Miel Picante",
    "category": "Frozen Pizza",
    "category_fr": "Pizza surgelée",
    "category_es": "Pizza congelada",
    "image": "Sausage-and-Hot-Honey-Frozen-Pizza.webp",
    "description": "Martha Stewart Sausage and Hot Honey Pizza pairs savory Italian sausage and fresh mozzarella with a drizzle of hot honey on a hand-stretched, stone-baked crust. The combination of savory sausage, creamy cheese and sweet heat creates a bold balance of flavors in every bite. Simply bake until golden for a distinctive, pizzeria-inspired pizza that's ready to enjoy at home in minutes.",
    "description_fr": "La pizza à la saucisse italienne et miel piquant Martha Stewart associe saucisse italienne de porc, mozzarella fondante et une touche de miel piquant sur une pâte dorée cuite sur pierre. Chaleur douce et gourmandise garanties.",
    "description_es": "La pizza de salchicha italiana y miel picante Martha Stewart ofrece una deliciosa combinación de salchicha italiana, queso fundido y miel con un toque picante horneada a la piedra.",
    "features": "Featuring: Fresh mozzarella, Italian sausage and hot honey",
    "features_fr": "Caractéristiques : Mozzarella fraîche, saucisse italienne et miel piquant",
    "features_es": "Características: Mozzarella fresca, salchicha italiana y miel picante",
    "gallery": [],
    "ingredients": "Ingredients: Wheat flour, water, mozzarella cheese, Italian sausage, hot honey, tomato sauce, olive oil, salt, yeast.\nContains: Wheat, Milk.",
    "ingredients_fr": "Ingrédients : Farine de blé, eau, fromage mozzarella, saucisse italienne, miel piquant, sauce tomate, huile d'olive, sel, levure.\nContient : Blé, Lait.",
    "ingredients_es": "Ingredientes: Harina de trigo, agua, queso mozzarella, salchicha italiana, miel picante, salsa de tomate, aceite de oliva, sal, levadura.\nContiene: Trigo, Leche."
  },
  {
    "id": 30,
    "title": "Spicy Garlic Infused Extra Virgin Olive Oil",
    "title_fr": "Huile d'Olive Extra Vierge Infusée à l'Ail Piquant",
    "title_es": "Aceite de Oliva Virgen Extra Infusionado con Ajo Picante",
    "category": "Infused Oils",
    "category_fr": "Huiles infusées",
    "category_es": "Aceites infusionados",
    "image": "Spicy-Garlic-Infused-Extra-Virgin-Olive-Oil.webp",
    "description": "Martha Stewart Spicy Garlic Infused Extra Virgin Olive Oil pairs extra virgin olive oil with garlic and crushed red pepper for a bold, savory flavor with just the right amount of heat. Drizzle it over oven-baked pizza for an instant upgrade, use it to finish pasta and roasted vegetables, or serve it with warm bread for dipping. For a simple appetizer, try it over warmed olives finished with fresh orange zest.",
    "description_fr": "L'huile d'olive extra vierge infusée à l'ail piquant Martha Stewart unit l'ail déshydraté et les piments rouges broyés à une huile d'olive extra vierge de choix. Rehausse instantanément pizzas, pâtes et trempettes de pain.",
    "description_es": "El aceite de oliva virgen extra infusionado con ajo picante Martha Stewart mezcla ajo y hojuelas de pimiento rojo para un sabor audaz y cálido. Magnífico para aderezar pizzas y verduras.",
    "features": "Featuring: Extra-virgin olive oil, garlic and crushed red pepper",
    "features_fr": "Caractéristiques : Huile d'olive extra vierge, ail et piment rouge broyé",
    "features_es": "Características: Aceite de oliva virgen extra, ajo y pimiento rojo triturado",
    "gallery": [],
    "ingredients": "Ingredients: Extra-virgin olive oil, crushed red pepper, dehydrated garlic, natural flavors (liquid garlic flavor).",
    "ingredients_fr": "Ingrédients : Huile d'olive extra vierge, piment rouge broyé, ail déshydraté, arômes naturels d'ail.",
    "ingredients_es": "Ingredientes: Aceite de oliva virgen extra, pimiento rojo triturado, ajo deshidratado, aromas naturales de ajo."
  },
  {
    "id": 31,
    "title": "Spinach Four Cheese With Alfredo Sauce Pinsa",
    "title_fr": "Pinsa Épinards et Quatre Fromages à la Sauce Alfredo",
    "title_es": "Pinsa de Espinacas y Cuatro Quesos con Salsa Alfredo",
    "category": "Frozen Pinsa",
    "category_fr": "Pinsa surgelée",
    "category_es": "Pinsa congelada",
    "image": "spinach-four-cheese-with-alfredo-sauce-pinsa-ca.webp",
    "description": "Martha Stewart Spinach Four Cheese with Alfredo Sauce Pinsa combines spinach with creamy Alfredo sauce and a rich blend of fontina, mozzarella, Parmesan and Romano cheeses on a hand-stretched, authentic Roman-style crust. The light, airy and crisp crust balances the creamy sauce and savory blend of cheeses, while spinach adds freshness to every bite. Rich and satisfying, it's an elevated Roman-inspired option that's ready to enjoy at home in minutes.",
    "description_fr": "La pinsa épinards et quatre fromages à la sauce Alfredo Martha Stewart marie épinards frais, sauce Alfredo crémeuse et une sélection généreuse de fromages fontina, mozzarella, parmesan et romano sur une pâte romaine au levain aérée et croustillante.",
    "description_es": "La pinsa de espinacas y cuatro quesos con salsa Alfredo Martha Stewart reúne espinacas, salsa blanca y una mezcla exquisita de quesos fontina, mozzarella, parmesano y romano sobre masa madre crujiente.",
    "features": "Featuring: Spinach, Alfredo sauce, fontina, mozzarella, Parmesan and Romano cheeses",
    "features_fr": "Caractéristiques : Épinards, sauce Alfredo, fromages fontina, mozzarella, parmesan et romano",
    "features_es": "Características: Espinacas, salsa Alfredo, quesos fontina, mozzarella, parmesano y romano",
    "gallery": [
      "spinach-four-cheese-with-alfredo-sauce-pinsa-gallery-1.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-gallery-2.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-gallery-3.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-gallery-4.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-gallery-5.webp"
    ],
    "ingredients": "Ingredients: Pinsa crust (wheat flour, organic rice flour, organic fava flour, sourdough yeast, water, olive oil, salt, yeast [yeast, sorbitan monostearate, ascorbic acid]). Toppings: Mozzarella cheese (milk, modified milk ingredients, cream, salt, calcium chloride, bacterial culture, microbial enzyme), Fontina cheese (milk, calcium chloride, bacterial culture, microbial enzyme, lipase), Spinach, Parmesan cheese (milk, salt, lipase, microbial enzyme, bacterial culture, calcium chloride, cellulose), Romano cheese (milk, salt, bacterial culture, lipase, calcium chloride, microbial enzyme, cellulose). Alfredo sauce: Cream (cream, milk, carrageenan, cellulose gum, mono and diglycerides, polysorbate 80), Minced garlic, Parmesan cheese (milk, salt, lipase, microbial enzyme, bacterial culture, calcium chloride, cellulose), Modified corn starch, Salt, Black pepper.\nContains: Wheat, Milk.\nMay contain: Eggs, Soy, Mustard.",
    "ingredients_fr": "Ingrédients : Pâte à pinsa (farine de blé, farine de riz bio, farine de fève bio, levain, eau, huile d'olive, sel, levure). Garnitures : Mozzarella, fontina, épinards, parmesan, romano. Sauce Alfredo : Crème, ail émincé, parmesan, amidon de maïs modifié, sel, poivre noir.\nContient : Blé, Lait.\nPeut contenir : Œufs, Soja, Moutarde.",
    "ingredients_es": "Ingredientes: Masa de pinsa (harina de trigo, harina de arroz orgánica, harina de haba orgánica, masa madre, agua, aceite de oliva, sal, levadura). Coberturas: Quesos mozzarella, fontina, parmesano, romano y espinacas. Salsa Alfredo: Crema, ajo picado, queso parmesano, sal, pimienta negra.\nContiene: Trigo, Leche.\nPuede contener: Huevos, Soya, Mostaza.",
    "slug": "spinach-four-cheese-with-alfredo-sauce-pinsa",
    "image_ca": "spinach-four-cheese-with-alfredo-sauce-pinsa-ca.webp",
    "image_us": "spinach-four-cheese-with-alfredo-sauce-pinsa-us.webp",
    "gallery_ca": [
      "spinach-four-cheese-with-alfredo-sauce-pinsa-gallery-1.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-gallery-2.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-gallery-3.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-gallery-4.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-gallery-5.webp"
    ],
    "gallery_us": [
      "spinach-four-cheese-with-alfredo-sauce-pinsa-us-gallery-1.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-us-gallery-2.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-us-gallery-3.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-us-gallery-4.webp",
      "spinach-four-cheese-with-alfredo-sauce-pinsa-us-gallery-5.webp"
    ]
  },
  {
    "id": 32,
    "title": "Spinach Four Cheese with Alfredo Pizza",
    "title_fr": "Pizza Épinards et Quatre Fromages à la Sauce Alfredo",
    "title_es": "Pizza de Espinacas y Cuatro Quesos con Salsa Alfredo",
    "category": "Frozen Pizza",
    "category_fr": "Pizza surgelée",
    "category_es": "Pizza congelada",
    "image": "Spinach-Four-Cheese-with-ALfredo-Frozen-Pizza.webp",
    "description": "Martha Stewart Spinach Four Cheese with Alfredo Pizza combines spinach with creamy Alfredo sauce and a rich blend of fontina, mozzarella, Parmesan and Romano cheeses on a hand-stretched, stone-baked crust. Rich and satisfying, it's an elevated option that's ready to enjoy at home in minutes.",
    "description_fr": "La pizza épinards et quatre fromages à la sauce Alfredo Martha Stewart allie épinards tendres, sauce Alfredo veloutée et un mélange gourmand de fontina, mozzarella, parmesan et romano sur une pâte cuite sur pierre.",
    "description_es": "La pizza de espinacas y cuatro quesos con salsa Alfredo Martha Stewart ofrece una deliciosa combinación de espinacas, salsa Alfredo y cuatro quesos italianos sobre masa horneada a la piedra.",
    "features": "Featuring: Spinach, Alfredo sauce, fontina, mozzarella, Parmesan and Romano cheeses",
    "features_fr": "Caractéristiques : Épinards, sauce Alfredo, fromages fontina, mozzarella, parmesan et romano",
    "features_es": "Características: Espinacas, salsa Alfredo, quesos fontina, mozzarella, parmesano y romano",
    "gallery": [],
    "ingredients": "Ingredients: Wheat flour, water, alfredo sauce, spinach, fontina cheese, mozzarella cheese, parmesan cheese, romano cheese, olive oil, salt, yeast.\nContains: Wheat, Milk.",
    "ingredients_fr": "Ingrédients : Farine de blé, eau, sauce alfredo, épinards, fromage fontina, fromage mozzarella, parmesan, romano, huile d'olive, sel, levure.\nContient : Blé, Lait.",
    "ingredients_es": "Ingredientes: Harina de trigo, agua, salsa alfredo, espinacas, quesos fontina, mozzarella, parmesano, romano, aceite de oliva, sal, levadura.\nContiene: Trigo, Leche."
  },
  {
    "id": 33,
    "aliasId": "prod_1790799592574",
    "slug": "organic-pinsa-crust",
    "title": "Organic Pinsa Crust",
    "title_fr": "Croûte de Pinsa Biologique",
    "title_es": "Masa de Pinsa Orgánica",
    "category": "Frozen Pinsa",
    "category_fr": "Pinsa surgelée",
    "category_es": "Pinsa congelada",
    "image": "organic-pinsa-crust.webp",
    "description": "Martha Stewart Organic Pinsa Crust is handcrafted using authentic Roman sourdough techniques and certified organic ingredients. With 20g of protein per serving, this light, airy, and naturally digestible crust delivers a crispy golden exterior and an irresistibly soft interior. Ready in minutes, it provides the ultimate artisan foundation for your favorite gourmet pizza creations at home.",
    "description_fr": "La croûte de pinsa biologique Martha Stewart est confectionnée artisanalement selon les méthodes romaines authentiques au levain et avec des ingrédients biologiques certifiés. Avec 20 g de protéines par portion, cette pâte légère, aérée et digeste offre un extérieur croustillant et une mie tendre. Prête en quelques minutes, elle est la base artisanale idéale pour vos pizzas gourmandes à la maison.",
    "description_es": "La masa de pinsa orgánica Martha Stewart está elaborada artesanalmente siguiendo la auténtica tradición romana con masa madre e ingredientes orgánicos certificados. Con 20 g de proteína por porción, esta masa ligera, esponjosa y de fácil digestión ofrece un exterior dorado crujiente y un interior suave y delicioso. Lista en minutos, es la base artesanal perfecta para sus creaciones gourmet en casa.",
    "features": "Pinsa is a light, crisp and authentic Italian flatbread, made with a carefully selected blend including organic einkorn, organic rice flour and organic fava flour, it is hand pressed and ready for bake at home.\u0003",
    "features_fr": "Caractéristiques : Croûte de pinsa biologique romaine étirée à la main au levain, 20 g de protéines, certifiée biologique (paquet de 2, poids net 2 x 230 g).",
    "features_es": "Características: Masa artesanal romana orgánica estirada a mano con masa madre, 20 g de proteína, certificada orgánica USDA (paquete de 2, peso neto 2 x 230 g).",
    "gallery": [
      "organic-pinsa-crust-gallery-1.webp",
      "organic-pinsa-crust-gallery-2.webp",
      "organic-pinsa-crust-gallery-3.webp",
      "organic-pinsa-crust-gallery-4.webp",
      "organic-pinsa-crust-gallery-5.webp"
    ],
    "ingredients": "Ingredients: Organic Flour Blend (Organic Wheat Flour, Organic Spelt Flour, Organic Einkorn Flour, Organic Rice Flour, Organic Fava Flour, Sourdough Yeast), Water, Salt, Organic Extra Virgin Olive Oil, Yeast (Yeast, Sorbitan Monostearate).\nContains: Wheat",
    "ingredients_fr": "Ingrédients : Mélange de farines biologiques (farine de blé biologique, farine d'épeautre biologique, farine d'engrain biologique, farine de riz biologique, farine de fève biologique, levain naturel), eau, sel, huile d'olive extra vierge biologique, levure.\nContient : Blé.",
    "ingredients_es": "Ingredientes: Mezcla de harinas orgánicas (harina de trigo orgánica, harina de espelta orgánica, harina de escaña orgánica, harina de arroz orgánica, harina de haba orgánica, levadura de masa madre), agua, sal, aceite de oliva virgen extra orgánico, levadura.\nContiene: Trigo.",
    "nutrition": "",
    "storage": "",
    "image_ca": "",
    "image_us": "organic-pinsa-crust-us.webp",
    "gallery_ca": [],
    "gallery_us": [
      "organic-pinsa-crust-us-gallery-1.webp",
      "organic-pinsa-crust-us-gallery-2.webp",
      "organic-pinsa-crust-us-gallery-3.webp",
      "organic-pinsa-crust-us-gallery-4.webp",
      "organic-pinsa-crust-us-gallery-5.webp"
    ]
  }
];
