backend:
  name: github
  repo: graphicsturpone-rgb/turpone-foods
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}” [skip cf]'
    update: 'Update {{collection}} “{{slug}}” [skip cf]'
    delete: 'Delete {{collection}} “{{slug}}” [skip cf]'
    uploadMedia: 'Upload “{{path}}” [skip cf]'
    deleteMedia: 'Delete “{{path}}” [skip cf]'

i18n:
  structure: multiple_folders
  locales: [en, fr, es]
  default_locale: en

media_folder: "assets/images/recipes"
public_folder: "/assets/images/recipes"

collections:
  - name: "recipes"
    label: "Recipes"
    folder: "content/recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Recipe Paragraph (Under Image)", name: "body", widget: "markdown", i18n: true}
      - {label: "Prep Time", name: "prepTime", widget: "string", default: "15 min"}
      - {label: "Cook Time", name: "cookTime", widget: "string", default: "30 min"}
      - {label: "Calories", name: "calories", widget: "string", default: "320 kcal"}
      - {label: "Yields", name: "yields", widget: "string", default: "4 servings"}
      - {label: "Recommended Product Image", name: "upsellImage", widget: "image", required: false}
      - {label: "Recommended Product Link", name: "upsellLink", widget: "string", required: false}
      - {label: "Ingredients", name: "ingredients", widget: "list", i18n: true, field: {label: "Ingredient", name: "ingredient", widget: "string"}}
      - {label: "Instructions", name: "instructions", widget: "list", i18n: true, field: {label: "Step", name: "step", widget: "markdown"}}
      - {label: "Nutrition Information", name: "nutrition", widget: "markdown", required: false, i18n: true}
